Support to string methods (contains, startswith, endswith, equals, isEmpty) to throw NPE (SymbolicStringHandler) GSoC'25 (#120)
* Add three way exploration of symbolic string

* Handle edge cases in the SymbolicStringHandler for the null choice: GSoC 2025

* Add 2 choices(EQUALS, NOTEQUAL) => null, in IFNULL bytecodeIns to contradict and execute then and the else side

* feat: Add support to IFNONNULL bytecode

* Add support isEmpty refactor

* Add test cases for testing npe (contains)

* Refactor npe.jpf

* Add trim support, roll back charAt and length

* Add final commit(code) with test cases for contains

* Refactor SymbolicStringHandler for equals

* Refactor SymbolicStringHandler for the null choice in handleBooleanStringInstructions

* Refactor and introduce new flag with the script additions

* Fix one error in svcomp script

* Refactor SymbolicStringHandler

* Refactored svcomp script

* Choices flipped for the IFNULL and IFNONNULL and also moved the test in one file

* listener flag in the script

* else case when npe flag is off and a concrete null is passed

diff --git a/jpf-sv-comp b/jpf-sv-comp
--- a/jpf-sv-comp
+++ b/jpf-sv-comp
@@ -29,6 +29,22 @@ if [ ! -s "${BM[0]}" ] || [ ! -s "$PROP_FILE" ] ; then
   exit 1
 fi
 
+echo "PROP_FILE=$PROP_FILE"
+  ASSERTION_MODE="FALSE"
+  RUNTIME_EXCEPTION_MODE="FALSE"
+  grep "assert" $PROP_FILE
+  if [ $? -eq 0 ]; then
+    ASSERTION_MODE="TRUE"
+  fi
+
+  grep "Exception" $PROP_FILE
+  if [ $? -eq 0 ]; then
+    RUNTIME_EXCEPTION_MODE="TRUE"
+  fi
+
+echo "ASSERTION_MODE=$ASSERTION_MODE"
+echo "RUNTIME_EXCEPTION_MODE=$RUNTIME_EXCEPTION_MODE"
+
 LOG=`mktemp -t jpf-log.XXXXXX`
 DIR=`mktemp -d -t jpf-benchmark.XXXXXX`
 
@@ -45,9 +61,16 @@ echo "symbolic.dp=z3bitvector" >> $DIR/config.jpf
 echo "symbolic.bvlength=64" >> $DIR/config.jpf
 echo "search.depth_limit=13" >> $DIR/config.jpf
 echo "symbolic.strings=true" >> $DIR/config.jpf
+echo "symbolic.string_dp=z3str3" >> $DIR/config.jpf
+echo "nullPointer.exception=false" >> $DIR/config.jpf
 echo "symbolic.string_dp_timeout_ms=3000" >> $DIR/config.jpf
 echo "symbolic.lazy=on" >> $DIR/config.jpf
 echo "symbolic.arrays=true" >> $DIR/config.jpf
+echo "listener = .symbc.SymbolicListener" >> $DIR/config.jpf
+if [ $RUNTIME_EXCEPTION_MODE = "TRUE" ] ; then
+  echo "runtime.exception=true" >> $DIR/config.jpf
+  #echo "search.multiple_errors = true" >> $DIR/config.jpf
+fi
 echo $DIR/config.jpf
 
 # run SPF
@@ -59,14 +82,48 @@ fi
 /usr/lib/jvm/java-8-openjdk-amd64/bin/java $JVM_FLAGS -jar $(pwd)/jpf-core/build/RunJPF.jar $DIR/config.jpf | tee $LOG
 
 # check the result
-grep "no errors detected" $LOG > /dev/null
-if [ $? -eq 0 ]; then
-  echo "SAFE"
-else
+if [ $ASSERTION_MODE = "TRUE" ]; then
+  echo "inside assertion_mode=true"
+
+  grep "no errors detected" $LOG > /dev/null
+  NO_ERRORS=$?
+
+  grep "java.lang.*Exception" $LOG > /dev/null
+  JAVA_EXCEPTION=$?
+
   grep "^error.*NoUncaughtExceptionsProperty.*AssertionError" $LOG > /dev/null
-  if [ $? -eq 0 ]; then
+  ASSERTION_ERROR=$?
+
+  if [ $NO_ERRORS -eq 0 ] || ([ $JAVA_EXCEPTION -eq 0 ] && [ $ASSERTION_ERROR -ne 0 ]); then
+    echo "SAFE"
+  elif [ $ASSERTION_ERROR -eq 0 ]; then
     echo "UNSAFE"
   else
     echo "UNKNOWN"
   fi
+
+elif [ $RUNTIME_EXCEPTION_MODE = "TRUE" ]; then
+  echo "inside runtime_exception_mode=true"
+
+  # Check for assertion errors AND no java exceptions OR no errors detected
+  grep "^error.*NoUncaughtExceptionsProperty.*AssertionError" $LOG > /dev/null
+  ASSERTION_ERROR=$?
+
+  grep "java.lang.*Exception" $LOG > /dev/null
+  JAVA_EXCEPTION=$?
+
+  grep "no errors detected" $LOG > /dev/null
+  NO_ERRORS=$?
+
+  if ([ $ASSERTION_ERROR -eq 0 ] && [ $JAVA_EXCEPTION -ne 0 ]) || [ $NO_ERRORS -eq 0 ]; then
+    echo "SAFE"
+  elif [ $JAVA_EXCEPTION -eq 0 ]; then
+    echo "UNSAFE"
+  else
+    echo "UNKNOWN"
+  fi
+
+else
+  echo "unsupported case. Failing"
+  exit 1
 fi
